### PR TITLE
git global config

### PR DESCRIPTION
**Pull request by vincekruger**
Added the GitHub workspace folder as a safe directory to the global config

Issue: #8

### CODE REVIEW

**Comment by vincekruger** [comment]
@darrynten ?

**Review by rickstaa — APPROVED** [review]
This is affecting my upstream actions too. Thanks for the PR @vincekruger. @UnicornGlobal Would be nice if it could be merged!

**Comment by vincekruger** [comment]
@rickstaa you could add an additional run command before checking for changes.

```yaml
- run: git config --global --add safe.directory
```

**Comment by rickstaa** [comment]
> ```yaml
> - run: git config --global --add safe.directory
> ```

Thanks for your quick response. I tried that already see https://github.com/sdr-enthusiasts/plane-alert-db/actions/runs/4382919640/jobs/7672535106, but it does only seem to affect my action code.

**Comment by rickstaa** [comment]
Here are some more details on why I think #9 needs to be merged into the main branch:

- The action fails without #9 -> https://github.com/sdr-enthusiasts/plane-alert-db/actions/runs/4383407477/jobs/7673615254
- The action works with #9 -> https://github.com/sdr-enthusiasts/plane-alert-db/actions/runs/4383479926/jobs/7673779130

**Comment by rickstaa** [comment]
> Here are some more details on why I think #9 needs to be merged into the main branch:
> 
> * The action fails without [git global config #9](https://github.com/UnicornGlobal/has-changes-action/pull/9) -> https://github.com/sdr-enthusiasts/plane-alert-db/actions/runs/4383407477/jobs/7673615254
> * The action works with [git global config #9](https://github.com/UnicornGlobal/has-changes-action/pull/9) -> https://github.com/sdr-enthusiasts/plane-alert-db/actions/runs/4383479926/jobs/7673779130

@vincekruger, did you see my last comment? It has no priority since I can use my fork, so take your time. I just wanted to double-check.

**Pull request closed without merging**
